// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('ABApp').controller('UserCtrl', [
    '$scope', function($scope) {
      $scope.tab = 'login';
      $scope.toLogin = function() {
        return $scope.tab = 'login';
      };
      return $scope.toRegister = function() {
        return $scope.tab = 'register';
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=user.js.map
