// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('ABApp').controller('MainCtrl');

  (function($scope) {
    $scope.tab = 'login';
    $scope.toLogin = function() {
      return $scope.tab = 'login';
    };
    $scope.toRegister(function() {
      return $scope.tab = 'register';
    });
    return void 0;
  });

}).call(this);

//# sourceMappingURL=veiw.js.map
