// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('ABApp').directive('abLogin', (function(_this) {
    return function() {
      return {
        templateUrl: 'views/login.html',
        restrict: 'E'
      };
    };
  })(this));

}).call(this);

//# sourceMappingURL=abLogin.js.map
