// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('ABApp').directive('abNavigate', function() {
    return {
      templateUrl: 'views/nav.html',
      restrict: 'E'
    };
  });

}).call(this);

//# sourceMappingURL=abNavigate.js.map
