// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('ABApp').directive('abRegister', (function(_this) {
    return function() {
      return {
        templateUrl: 'views/register.html',
        restrict: 'E'
      };
    };
  })(this));

}).call(this);

//# sourceMappingURL=abRegister.js.map
