// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('ABApp', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute']).config([
    '$routeProvider', (function(_this) {
      return function($routeProvider) {
        return $routeProvider.when('/', {
          templateUrl: 'views/main.html',
          controller: 'MainCtrl'
        }).when('/login', {
          templateUrl: 'views/user.html',
          controller: 'UserCtrl'
        }).otherwise({
          redirectTo: '/'
        });
      };
    })(this)
  ]);

}).call(this);

//# sourceMappingURL=app.js.map
